runtime: php55
api_version: 1

# [START handlers]
handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /(.+\.php)$
  script: \1
  
- url: /
  script: login.php
# [END handlers]

